import Link from "next/link";

export default function Home() {
  return (
    <main className="site-shell">
      <header className="topbar"><Link className="wordmark" href="/">mạch<span>.</span></Link><nav className="nav" aria-label="Điều hướng chính"><Link className="active" href="/">Trang chủ</Link><Link href="/blog">Tất cả bài viết</Link><Link href="/blog/authors">Tác giả</Link><Link className="nav-cta" href="/blog">Đọc mới nhất ↗</Link></nav></header>
      <section className="hero"><div><div className="eyebrow">Tạp chí độc lập · Số 01</div><h1>Những điều nhỏ bé làm nên <em>một đời sống lớn.</em></h1><p className="hero-copy">Mạch là nơi những ý tưởng về công nghệ, văn hóa và cách chúng ta sống cùng nhau được kể lại bằng sự tò mò và một chút chậm rãi.</p><Link className="button-link" href="/blog/nhung-thanh-pho-khong-ngu">Đọc câu chuyện nổi bật <span>→</span></Link></div><div className="feature-art" aria-label="Hình minh họa màu san hô và xanh chanh"><span className="art-label">Cover story / 01</span></div></section>
      <section><div className="section-head"><h2 className="section-title">Đọc gần đây</h2><Link className="view-all" href="/blog">Xem tất cả →</Link></div><div className="story-grid"><article className="story-card"><Link href="/blog/nhung-thanh-pho-khong-ngu"><div className="story-art art-amber"><span className="art-label">01</span></div><div className="story-meta">Đời sống · 8 phút đọc</div><h3>Những thành phố không ngủ, và người học cách nghỉ ngơi</h3><p>Về nhịp sống mới đang được viết lại sau giờ tan ca.</p></Link></article><article className="story-card"><Link href="/blog/ky-nguyen-cua-su-chu-y"><div className="story-art art-blue"><span className="art-label">02</span></div><div className="story-meta">Công nghệ · 6 phút đọc</div><h3>Kỷ nguyên của sự chú ý: ta đang thực sự chọn gì?</h3><p>Một cuộc trò chuyện về những khoảng trống cần thiết.</p></Link></article><article className="story-card"><Link href="/blog/bep-nho-va-the-gioi-lon"><div className="story-art art-red"><span className="art-label">03</span></div><div className="story-meta">Văn hóa · 5 phút đọc</div><h3>Căn bếp nhỏ và cách nó mở cửa ra thế giới</h3><p>Những ký ức có mùi khói, gừng và tiếng dao thớt.</p></Link></article></div></section>
      <section className="newsletter"><div><h2>Thư từ Mạch.</h2><p>Một lá thư ngắn vào mỗi sáng thứ Tư.</p></div><form><input type="email" placeholder="Email của bạn" aria-label="Email của bạn" /><button type="submit">Đăng ký</button></form></section><footer className="footer"><span>© 2026 Mạch Magazine</span><span>Được làm cho những người còn tò mò.</span></footer>
    </main>
  );
}
